variable "availability_domain" {}
variable "airflow_database" {}
variable "mysqladmin_password" {}
variable "mysqladmin_username" {}
variable "compartment_ocid" {}
variable "mysql_shape" {}
variable "subnet_id" {}
variable "enable_mysql_backups" {}
variable "oci_mysql_ip" {}
